spring:
  application:
    name: gomdolog
  datasource:
    url: jdbc:mysql://localhost:3306/gomdolog
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 20
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: caches, metrics

jwt:
  token:
    secret: 4rZceoPO8qHVJcMPNJp9fTmKrbwm/6gEOQEf2fEdaUo=

llm:
  api: http://localhost:8000
  secret: u453BdMu69dC1m8+u4iUNOZ0VFYmTWRE0LiFocxU++g=
